export const apiEndpoints = {
  commandCenter: "/api/command-center",
  decisionEngine: "/api/decision-engine",
  business: "/api/business",
  finance: "/api/finance",
  advertising: "/api/advertising",
  products: "/api/products",
  inventory: "/api/inventory",
  advisor: "/api/advisor",
  advisorQuery: "/api/advisor/query",
  authSession: "/api/auth/session",
  authProfile: "/api/auth/profile",
  organization: "/api/organization",
  organizations: "/api/organizations",
  organizationsSelect: "/api/organizations/select",
  exports: "/api/exports",
  schedules: "/api/schedules",
  jobs: "/api/jobs",
  notifications: "/api/notifications",
  notificationRules: "/api/notifications/rules",
  notificationHistory: "/api/notifications/history",
  notificationChannels: "/api/notifications/channels",
  notificationTest: "/api/notifications/test",
  status: "/api/status",
  version: "/api/version",
  wbCabinet: "/api/wb-cabinet",
  wbCabinets: "/api/wb-cabinets",
  wbCabinetsSelect: "/api/wb-cabinets/select",
  wbCabinetConnect: "/api/wb-cabinet/connect",
  wbCabinetDisconnect: "/api/wb-cabinet/disconnect",
  workspaceContext: "/api/workspace/context",
  reports: "/api/reports",
  users: "/api/users",
  audit: "/api/audit"
} as const;

export type ApiEndpointName = keyof typeof apiEndpoints;
