from __future__ import annotations


def _command_handlers():
    from .handlers.admin import admin_command, apistatus_command, health_command, syncstatus_command
    from .handlers.advertising import ads_command, adsaudit_command, adsupdate_command, advert_command
    from .handlers.advisor import advisor_command
    from .handlers.analytics import analytics_command
    from .handlers.business import business_command
    from .handlers.connect import connect_command, disconnect_command
    from .handlers.developer import (
        control_command,
        data_command,
        migration_command,
        performance_command,
        rc_command,
        structure_command,
        telegram_command,
        ui_command,
    )
    from .handlers.finance import finance_command
    from .handlers.legacy import adsfullstatsprobe_command
    from .handlers.navigation import home_command, menu_command
    from .handlers.products import products_command
    from .handlers.profile import account_command, profile_command
    from .handlers.profit import (
        abc_command,
        cashflow_command,
        categories_command,
        expense_command,
        losers_command,
        profit_command,
        topprofit_command,
    )
    from .handlers.reports import dashboard_command, report_command
    from .handlers.sales import orders_command, sales_command
    from .handlers.start import start_command
    from .handlers.stocks import forecast_command, replenishment_command, stock_command, stocks_command
    from .handlers.system import system_command
    from .handlers.update import update_command
    from .legacy_bot import (
        buy_command,
        card_command,
        ceo_command,
        cfo_command,
        command_command,
        compare_command,
        competitor_command,
        cost_command,
        decision_command,
        director_command,
        export_command,
        financial_command,
        funnel_command,
        gold_command,
        kpi_command,
        money_command,
        month_command,
        morning_command,
        notify_command,
        payment_command,
        period_command,
        plan_command,
        pnl_command,
        prices_command,
        problems_command,
        product_command,
        ref_command,
        sku_command,
        status_command,
        tariff_command,
        tax_command,
        today_command,
        udl_command,
        unified_command,
        week_command,
        advice_command,
    )

    return {
        "start": start_command,
        "help": menu_command,
        "menu": menu_command,
        "connect": connect_command,
        "disconnect": disconnect_command,
        "update": update_command,
        "ads": ads_command,
        "adsupdate": adsupdate_command,
        "adsaudit": adsaudit_command,
        "adsfullstatsprobe": adsfullstatsprobe_command,
        "apistatus": apistatus_command,
        "syncstatus": syncstatus_command,
        "tax": tax_command,
        "tariff": tariff_command,
        "buy": buy_command,
        "pro": buy_command,
        "profile": profile_command,
        "ref": ref_command,
        "ceo": ceo_command,
        "morning": morning_command,
        "report": report_command,
        "dashboard": dashboard_command,
        "payment": payment_command,
        "money": money_command,
        "business": business_command,
        "director": director_command,
        "home": home_command,
        "udl": udl_command,
        "unified": unified_command,
        "period": period_command,
        "command": command_command,
        "migration": migration_command,
        "control": control_command,
        "structure": structure_command,
        "rc": rc_command,
        "performance": performance_command,
        "cfo": cfo_command,
        "decision": decision_command,
        "kpi": kpi_command,
        "today": today_command,
        "week": week_command,
        "month": month_command,
        "orders": orders_command,
        "funnel": funnel_command,
        "advert": advert_command,
        "analytics": analytics_command,
        "product": product_command,
        "products": products_command,
        "stocks": stocks_command,
        "stock": stock_command,
        "forecast": forecast_command,
        "replenishment": replenishment_command,
        "finance": finance_command,
        "financial": financial_command,
        "gold": gold_command,
        "data": data_command,
        "profit": profit_command,
        "advisor": advisor_command,
        "account": account_command,
        "sales": sales_command,
        "sku": sku_command,
        "topprofit": topprofit_command,
        "losers": losers_command,
        "expense": expense_command,
        "pnl": pnl_command,
        "problems": problems_command,
        "advice": advice_command,
        "categories": categories_command,
        "plan": plan_command,
        "compare": compare_command,
        "cashflow": cashflow_command,
        "prices": prices_command,
        "export": export_command,
        "notify": notify_command,
        "competitor": competitor_command,
        "card": card_command,
        "cost": cost_command,
        "abc": abc_command,
        "health": health_command,
        "system": system_command,
        "status": status_command,
        "telegram": telegram_command,
        "ui": ui_command,
        "admin": admin_command,
    }
